"""Anonymous visitor tracking: ingest, plus the admin read side.

The whole point of this router is that it works for people who do not have an
account yet. Someone lands on the site, gets shown the login/register screen,
pokes at it, and leaves -- none of that is visible in `users` or `bets`, so it
is recorded here instead.

Trust model. `/api/track` is public, because it has to be: there is no token
before someone registers. So nothing that matters is taken from the request
body. The IP and the User-Agent are read from the connection and the headers
by the server, event names are checked against a whitelist, and every string
is length-capped. The client only gets to say *which* of a known set of things
happened and on which path.

What a session's `active_seconds` means: time the tab was actually visible,
summed from the client's heartbeats. It is deliberately not "last event minus
first event", which would count a tab forgotten in a background window as
half an hour of interest.
"""

import json
import re
from typing import Optional

from fastapi import APIRouter, Depends, Header, HTTPException, Request
from pydantic import BaseModel

from database import get_db_connection
from deps import require_admin

router = APIRouter(tags=["analytics"])

# Only these can be recorded. An open event name would let anyone fill the
# table with junk that the dashboard would then present as real behaviour.
EVENTS = {
    "session_start",     # first hit of a visit
    "page_view",         # any screen, including the sub-page router's screens
    "auth_view",         # the login/register screen came into view
    "auth_tab",          # switched between the login and register tabs
    "field_focus",       # started filling a field (meta.field)
    "register_submit",
    "register_success",
    "register_failed",
    "login_submit",
    "login_success",
    "login_failed",
    "heartbeat",         # still here, tab visible (meta.seconds)
    "exit",              # tab hidden or closing (meta.seconds)
}

# Events that decide how a session is finally labelled.
OUTCOMES = {
    "register_success": "registered",
    "login_success": "logged_in",
}

MAX_ID = 64
MAX_TEXT = 512
MAX_META_KEYS = 12
# One heartbeat should never claim more than a couple of minutes of attention;
# a client that sleeps and wakes must not be able to inflate its own dwell time.
MAX_HEARTBEAT_SECONDS = 180


class TrackRequest(BaseModel):
    visitor_id: str
    session_id: str
    event: str
    path: Optional[str] = None
    referrer: Optional[str] = None
    meta: Optional[dict] = None


def _clean(value: Optional[str], limit: int = MAX_TEXT) -> Optional[str]:
    if value is None:
        return None
    return str(value).strip()[:limit] or None


def _valid_id(value: str) -> bool:
    """Ids are generated by the tracker; accept only that shape."""
    return bool(value) and len(value) <= MAX_ID and re.fullmatch(r"[A-Za-z0-9_-]+", value)


def client_ip(request: Request, forwarded: Optional[str]) -> Optional[str]:
    """The visitor's IP, as seen through Vercel's and Render's proxies.

    `request.client.host` behind a proxy is the proxy, so X-Forwarded-For is
    the real source. Its first entry is the original client; the rest are the
    hops, and only the first is meaningful here.
    """
    if forwarded:
        first = forwarded.split(",")[0].strip()
        if first:
            return first[:64]
    return request.client.host if request.client else None


def parse_user_agent(ua: str) -> tuple:
    """(browser, os, device) from a User-Agent string.

    Deliberately a small hand-rolled matcher rather than a dependency: the
    dashboard needs a readable label, not device-database precision, and the
    order below matters because these strings deliberately impersonate each
    other (every Chrome UA also says "Safari", Edge says "Chrome").
    """
    ua = ua or ""
    lowered = ua.lower()

    if "edg/" in lowered:
        browser = "Edge"
    elif "opr/" in lowered or "opera" in lowered:
        browser = "Opera"
    elif "samsungbrowser" in lowered:
        browser = "Samsung Internet"
    elif "miuibrowser" in lowered:
        browser = "MI Browser"
    elif "ucbrowser" in lowered:
        browser = "UC Browser"
    elif "firefox/" in lowered:
        browser = "Firefox"
    elif "chrome/" in lowered:
        browser = "Chrome"
    elif "safari/" in lowered:
        browser = "Safari"
    else:
        browser = "Other"

    if "android" in lowered:
        os_name = "Android"
    elif "iphone" in lowered or "ipad" in lowered or "ios" in lowered:
        os_name = "iOS"
    elif "windows" in lowered:
        os_name = "Windows"
    elif "mac os" in lowered or "macintosh" in lowered:
        os_name = "macOS"
    elif "linux" in lowered:
        os_name = "Linux"
    else:
        os_name = "Other"

    if "ipad" in lowered or "tablet" in lowered:
        device = "Tablet"
    elif "mobi" in lowered or "android" in lowered or "iphone" in lowered:
        device = "Mobile"
    else:
        device = "Desktop"

    return browser, os_name, device


def _safe_meta(meta: Optional[dict]) -> Optional[str]:
    if not isinstance(meta, dict) or not meta:
        return None
    trimmed = {}
    for key, value in list(meta.items())[:MAX_META_KEYS]:
        key = str(key)[:40]
        if isinstance(value, (int, float, bool)) or value is None:
            trimmed[key] = value
        else:
            trimmed[key] = str(value)[:200]
    return json.dumps(trimmed)


@router.post("/api/track")
def track(
    req: TrackRequest,
    request: Request,
    x_forwarded_for: Optional[str] = Header(None),
    user_agent: Optional[str] = Header(None),
):
    if req.event not in EVENTS:
        raise HTTPException(status_code=400, detail="Unknown event.")
    if not _valid_id(req.visitor_id) or not _valid_id(req.session_id):
        raise HTTPException(status_code=400, detail="Invalid tracking id.")

    ip = client_ip(request, x_forwarded_for)
    browser, os_name, device = parse_user_agent(user_agent or "")
    path = _clean(req.path)
    meta = req.meta if isinstance(req.meta, dict) else {}

    # Only heartbeat/exit carry time, and it is clamped: an honest client sends
    # one heartbeat per interval, a dishonest one cannot buy engagement.
    seconds = 0
    if req.event in ("heartbeat", "exit"):
        try:
            seconds = max(0, min(int(float(meta.get("seconds", 0))), MAX_HEARTBEAT_SECONDS))
        except (TypeError, ValueError):
            seconds = 0

    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        # First event of a visit creates the session; later ones only extend
        # it. ON CONFLICT DO NOTHING keeps two events racing on page load from
        # producing a duplicate-key error.
        cursor.execute(
            """
            INSERT INTO visitor_sessions
                (id, visitor_id, ip, user_agent, browser, os, device,
                 referrer, landing_path, last_path, page_views)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
            ON CONFLICT (id) DO NOTHING
            """,
            (
                req.session_id, req.visitor_id, ip, _clean(user_agent), browser,
                os_name, device, _clean(req.referrer), path, path,
            ),
        )

        # `session_start` is excluded from last_path: it carries the landing
        # path, and a late one would otherwise drag the "furthest screen
        # reached" back to where the visit began.
        advances_path = None if req.event == "session_start" else path
        cursor.execute(
            """
            UPDATE visitor_sessions
               SET last_seen_at = NOW(),
                   last_path = COALESCE(?, last_path),
                   page_views = page_views + ?,
                   active_seconds = active_seconds + ?
             WHERE id = ?
            """,
            (advances_path, 1 if req.event == "page_view" else 0, seconds, req.session_id),
        )

        # The landing path is whatever `session_start` says, never whichever
        # request happened to arrive first. The client serialises its events,
        # but a retry or a slow network can still reorder them, and a session
        # that reports landing on the page it *finished* on is worse than
        # useless -- it inverts the journey the dashboard is meant to show.
        if req.event == "session_start" and path:
            cursor.execute(
                "UPDATE visitor_sessions SET landing_path = ? WHERE id = ?",
                (path, req.session_id),
            )

        if req.event in OUTCOMES:
            # Only ever moves forward: a later page_view must not knock a
            # session back to "browsing" after it converted.
            cursor.execute(
                "UPDATE visitor_sessions SET outcome = ? WHERE id = ?",
                (OUTCOMES[req.event], req.session_id),
            )

        cursor.execute(
            """
            INSERT INTO visitor_events (session_id, visitor_id, name, path, meta)
            VALUES (?, ?, ?, ?, ?)
            """,
            (req.session_id, req.visitor_id, req.event, path, _safe_meta(req.meta)),
        )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    return {"status": "ok"}


class IdentifyRequest(BaseModel):
    visitor_id: str
    session_id: str
    user_id: str


@router.post("/api/track/identify")
def identify(req: IdentifyRequest):
    """Attach a session to the account it just created or signed into.

    Separate from `/api/track` because this is the one write that joins the
    anonymous world to a real user, and it must not fabricate that link: the
    user id is only accepted if it actually exists.
    """
    if not _valid_id(req.visitor_id) or not _valid_id(req.session_id):
        raise HTTPException(status_code=400, detail="Invalid tracking id.")

    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        user = cursor.execute(
            "SELECT id FROM users WHERE id = ?", (req.user_id[:MAX_ID],)
        ).fetchone()
        if not user:
            raise HTTPException(status_code=404, detail="Unknown user.")
        cursor.execute(
            "UPDATE visitor_sessions SET user_id = ?, last_seen_at = NOW() WHERE id = ?",
            (user["id"], req.session_id),
        )
        # Backfill earlier anonymous visits by the same browser, so the admin
        # can see everything that person did before they signed up.
        cursor.execute(
            "UPDATE visitor_sessions SET user_id = ? WHERE visitor_id = ? AND user_id IS NULL",
            (user["id"], req.visitor_id),
        )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
    return {"status": "ok"}


# ------------------------------------------------------------------ admin read

@router.get("/api/admin/visitors/summary")
def visitors_summary(hours: int = 24, _: bool = Depends(require_admin)):
    """The funnel: landed -> saw the auth screen -> tried -> converted."""
    hours = max(1, min(hours, 24 * 90))
    window = f"{hours} hours"

    conn = get_db_connection()
    try:
        row = conn.execute(
            """
            SELECT COUNT(*) AS sessions,
                   COUNT(DISTINCT visitor_id) AS visitors,
                   COUNT(*) FILTER (WHERE outcome = 'registered') AS registered,
                   COUNT(*) FILTER (WHERE outcome = 'logged_in') AS logged_in,
                   COUNT(*) FILTER (WHERE outcome = 'browsing') AS still_anonymous,
                   COUNT(*) FILTER (WHERE page_views <= 1 AND active_seconds < 10) AS bounced,
                   COALESCE(ROUND(AVG(active_seconds)), 0) AS avg_seconds,
                   COALESCE(ROUND(AVG(active_seconds) FILTER (WHERE outcome = 'browsing')), 0)
                       AS avg_seconds_anonymous
            FROM visitor_sessions
            WHERE started_at >= NOW() - ?::interval
            """,
            (window,),
        ).fetchone()

        funnel = conn.execute(
            """
            SELECT COUNT(DISTINCT session_id) FILTER (WHERE name = 'auth_view') AS saw_auth,
                   COUNT(DISTINCT session_id) FILTER (WHERE name = 'field_focus') AS started_typing,
                   COUNT(DISTINCT session_id) FILTER (WHERE name = 'register_submit') AS tried_register,
                   COUNT(DISTINCT session_id) FILTER (WHERE name = 'login_submit') AS tried_login,
                   COUNT(DISTINCT session_id) FILTER (WHERE name IN ('register_failed','login_failed'))
                       AS had_failure
            FROM visitor_events
            WHERE created_at >= NOW() - ?::interval
            """,
            (window,),
        ).fetchone()

        devices = conn.execute(
            """
            SELECT device, browser, COUNT(*) AS sessions
            FROM visitor_sessions
            WHERE started_at >= NOW() - ?::interval
            GROUP BY device, browser ORDER BY sessions DESC LIMIT 10
            """,
            (window,),
        ).fetchall()
    finally:
        conn.close()

    landed = int(row["sessions"] or 0)
    converted = int(row["registered"] or 0) + int(row["logged_in"] or 0)
    return {
        "hours": hours,
        "visitors": int(row["visitors"] or 0),
        "sessions": landed,
        "registered": int(row["registered"] or 0),
        "logged_in": int(row["logged_in"] or 0),
        "still_anonymous": int(row["still_anonymous"] or 0),
        "bounced": int(row["bounced"] or 0),
        "avg_seconds": int(row["avg_seconds"] or 0),
        "avg_seconds_anonymous": int(row["avg_seconds_anonymous"] or 0),
        # Undefined with no traffic -- None rather than a flattering 0%.
        "conversion_rate": round(converted / landed * 100, 1) if landed else None,
        "funnel": {
            "landed": landed,
            "saw_auth": int(funnel["saw_auth"] or 0),
            "started_typing": int(funnel["started_typing"] or 0),
            "tried_register": int(funnel["tried_register"] or 0),
            "tried_login": int(funnel["tried_login"] or 0),
            "had_failure": int(funnel["had_failure"] or 0),
            "converted": converted,
        },
        "devices": [dict(entry) for entry in devices],
    }


@router.get("/api/admin/visitors")
def visitors(
    hours: int = 24,
    outcome: Optional[str] = None,
    limit: int = 100,
    _: bool = Depends(require_admin),
):
    hours = max(1, min(hours, 24 * 90))
    limit = max(1, min(limit, 500))
    params = [f"{hours} hours"]
    clause = ""
    # The outcome filter is interpolated only after being matched against this
    # fixed set, so nothing from the query string reaches the SQL text.
    if outcome in ("browsing", "registered", "logged_in"):
        clause = "AND s.outcome = ?"
        params.append(outcome)
    params.append(limit)

    conn = get_db_connection()
    try:
        rows = conn.execute(
            f"""
            SELECT s.*, u.username, u.phone
            FROM visitor_sessions s
            LEFT JOIN users u ON u.id = s.user_id
            WHERE s.started_at >= NOW() - ?::interval
              {clause}
            ORDER BY s.last_seen_at DESC
            LIMIT ?
            """,
            params,
        ).fetchall()
    finally:
        conn.close()

    return {
        "sessions": [
            {
                **dict(row),
                "started_at": str(row["started_at"]),
                "last_seen_at": str(row["last_seen_at"]),
            }
            for row in rows
        ]
    }


@router.get("/api/admin/visitors/daily")
def visitors_daily(days: int = 60, _: bool = Depends(require_admin)):
    """Visitor sessions grouped into one bucket per calendar day.

    Declared before the /{session_id} route so "daily" is never mistaken for a
    session id. Each day carries that day's sessions plus its own totals.
    """
    days = max(1, min(days, 365))
    conn = get_db_connection()
    try:
        rows = conn.execute(
            """
            SELECT s.id, s.visitor_id, s.ip, s.device, s.browser, s.os,
                   s.landing_path, s.last_path, s.page_views, s.active_seconds,
                   s.outcome, s.started_at, s.user_id, u.username, u.phone
            FROM visitor_sessions s
            LEFT JOIN users u ON u.id = s.user_id
            WHERE s.started_at >= NOW() - ?::interval
            ORDER BY s.started_at DESC
            """,
            (f"{days} days",),
        ).fetchall()
    finally:
        conn.close()

    days_map = {}
    for row in rows:
        started = row["started_at"]
        key = started.date().isoformat()
        bucket = days_map.setdefault(
            key,
            {
                "date": key,
                "label": started.strftime("%A, %d %B %Y"),
                "sessions": 0,
                "visitors": set(),
                "registered": 0,
                "logged_in": 0,
                "anonymous": 0,
                "bounced": 0,
                "seconds_total": 0,
                "rows": [],
            },
        )
        seconds = int(row["active_seconds"] or 0)
        bucket["sessions"] += 1
        bucket["visitors"].add(row["visitor_id"])
        bucket["seconds_total"] += seconds
        outcome = row["outcome"] or "browsing"
        if outcome == "registered":
            bucket["registered"] += 1
        elif outcome == "logged_in":
            bucket["logged_in"] += 1
        else:
            bucket["anonymous"] += 1
        if int(row["page_views"] or 0) <= 1 and seconds < 10:
            bucket["bounced"] += 1
        bucket["rows"].append(
            {
                "id": row["id"],
                "time": started.strftime("%H:%M"),
                "visitor": row["username"] or (row["visitor_id"][:10] + "…"),
                "phone": row["phone"],
                "ip": row["ip"],
                "device": f'{row["device"] or "?"} · {row["browser"] or "?"}',
                "journey": f'{row["landing_path"] or "?"} → {row["last_path"] or "?"}',
                "seconds": seconds,
                "outcome": outcome,
            }
        )

    result = []
    for day in sorted(days_map.values(), key=lambda d: d["date"], reverse=True):
        count = day["sessions"]
        result.append(
            {
                "date": day["date"],
                "label": day["label"],
                "sessions": count,
                "visitors": len(day["visitors"]),
                "registered": day["registered"],
                "logged_in": day["logged_in"],
                "anonymous": day["anonymous"],
                "bounced": day["bounced"],
                "avg_seconds": round(day["seconds_total"] / count) if count else 0,
                "rows": day["rows"],
            }
        )
    return {"days": result}


@router.get("/api/admin/visitors/{session_id}")
def visitor_timeline(session_id: str, _: bool = Depends(require_admin)):
    """Everything one visit did, in order -- the 'kis page tak aaya' view."""
    conn = get_db_connection()
    try:
        session = conn.execute(
            """
            SELECT s.*, u.username, u.phone
            FROM visitor_sessions s
            LEFT JOIN users u ON u.id = s.user_id
            WHERE s.id = ?
            """,
            (session_id,),
        ).fetchone()
        if not session:
            raise HTTPException(status_code=404, detail="Session not found.")
        events = conn.execute(
            """
            SELECT name, path, meta, created_at FROM visitor_events
            WHERE session_id = ? ORDER BY created_at, id
            """,
            (session_id,),
        ).fetchall()
        # Other visits from the same browser, so a returning stranger reads as
        # one person rather than a row per visit.
        other = conn.execute(
            """
            SELECT id, started_at, outcome, active_seconds, page_views
            FROM visitor_sessions
            WHERE visitor_id = ? AND id <> ?
            ORDER BY started_at DESC LIMIT 20
            """,
            (session["visitor_id"], session_id),
        ).fetchall()
    finally:
        conn.close()

    return {
        "session": {
            **dict(session),
            "started_at": str(session["started_at"]),
            "last_seen_at": str(session["last_seen_at"]),
        },
        "events": [
            {**dict(event), "created_at": str(event["created_at"])} for event in events
        ],
        "other_visits": [
            {**dict(visit), "started_at": str(visit["started_at"])} for visit in other
        ],
    }
